//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win11Check.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Win11Check.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _25231 {
            get {
                object obj = ResourceManager.GetObject("25231", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _32officeicons_31_89708 {
            get {
                object obj = ResourceManager.GetObject("32officeicons-31_89708", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _569px_Letter_x_svg {
            get {
                object obj = ResourceManager.GetObject("569px-Letter_x.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _5ca5bf1dff3c03fbf7cc9b3c_Kofi_logo_RGB_rounded {
            get {
                object obj = ResourceManager.GetObject("5ca5bf1dff3c03fbf7cc9b3c_Kofi_logo_RGB_rounded", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap check {
            get {
                object obj = ResourceManager.GetObject("check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap loading_buffering {
            get {
                object obj = ResourceManager.GetObject("loading-buffering", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ProcessorAMDList&gt;
        ///&lt;processor&gt;3015e&lt;/processor&gt;
        ///&lt;processor&gt;3020e&lt;/processor&gt;
        ///&lt;processor&gt;Athlon Gold 3150C&lt;/processor&gt;
        ///&lt;processor&gt;Athlon Gold 3150U&lt;/processor&gt;
        ///&lt;processor&gt;Athlon Silver 3050C&lt;/processor&gt;
        ///&lt;processor&gt;Athlon Silver 3050e&lt;/processor&gt;
        ///&lt;processor&gt;Athlon Silver 3050U&lt;/processor&gt;
        ///&lt;processor&gt;Athlon 3000G&lt;/processor&gt;
        ///&lt;processor&gt;Athlon 300GE&lt;/processor&gt;
        ///&lt;processor&gt;Athlon 300U&lt;/processor&gt;
        ///&lt;processor&gt;Athlon 320GE&lt;/processor&gt;
        ///&lt;processor&gt;Athlon Gold 3150G [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string SupportedProcessorsAMD {
            get {
                return ResourceManager.GetString("SupportedProcessorsAMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ProcessorIntelList&gt;
        ///&lt;processor&gt;Atom(R) x6200FE&lt;/processor&gt;
        ///&lt;processor&gt;Atom(R) x6211E&lt;/processor&gt;
        ///&lt;processor&gt;Atom(R) x6212RE&lt;/processor&gt;
        ///&lt;processor&gt;Atom(R) x6413E&lt;/processor&gt;
        ///&lt;processor&gt;Atom(R) x6414RE&lt;/processor&gt;
        ///&lt;processor&gt;Atom(R) x6425E&lt;/processor&gt;
        ///&lt;processor&gt;Atom(R) x6425RE&lt;/processor&gt;
        ///&lt;processor&gt;Atom(R) x6427FE&lt;/processor&gt;
        ///&lt;processor&gt;Celeron(R) G4900&lt;/processor&gt;
        ///&lt;processor&gt;Celeron(R) G4900T&lt;/processor&gt;
        ///&lt;processor&gt;Celeron(R) G4920&lt;/processor&gt;
        ///&lt;process [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string SupportedProcessorsIntel {
            get {
                return ResourceManager.GetString("SupportedProcessorsIntel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ProcessorQualcommlList&gt;
        ///	&lt;processor&gt;Snapdragon (TM) 850&lt;/processor&gt;
        ///	&lt;processor&gt;Snapdragon (TM) 7c&lt;/processor&gt;
        ///	&lt;processor&gt;Snapdragon (TM) 8c&lt;/processor&gt;
        ///	&lt;processor&gt;Snapdragon (TM) 8cx&lt;/processor&gt;
        ///	&lt;processor&gt;Microsoft SQ1&lt;/processor&gt;
        ///	&lt;processor&gt;Microsoft SQ2&lt;/processor&gt;
        ///&lt;/ProcessorQualcommlList&gt;.
        /// </summary>
        public static string SupportedProcessorsQualcomm {
            get {
                return ResourceManager.GetString("SupportedProcessorsQualcomm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap x_30465_640 {
            get {
                object obj = ResourceManager.GetObject("x_30465_640", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
